config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  resources :questions do
    put :hide, on: :member
  end

  resource :session, only: %i[new create destroy]
  resources :users, param: :nickname, except: %i[index]
  resources :hashtags, param: :text, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  HASHTAG_FORMAT = /#[[:word:]-]+/

  has_and_belongs_to_many :questions

  validates :text, presence: true, length: { maximum: 280 }

  scope :with_questions, -> { where_exists(:questions) }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true
  has_and_belongs_to_many :hashtags

  validates :body, presence: true, length: { maximum: 280 }

  after_save_commit :create_hashtags

  def create_hashtags
    self.hashtags =
      get_question_hashtags.map { |hashtag| Hashtag.create_or_find_by(text: hashtag.delete('#')) }
  end

  def get_question_hashtags
    full_text = "#{body} #{answer}"
    has_hashtags(full_text.downcase).uniq
  end

  private

  def has_hashtags(text)
    text.scan(Hashtag::HASHTAG_FORMAT)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic(secure: true, filetype: :png, size: 100, default: 'retro')

  NICKNAME_FORMAT = /\A[a-z_0-9]+\z/
  EMAIL_FORMAT = /\A[a-z\d_+.\-]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  COLOR_FORMAT = /\A#\h{3}{1,2}\z/

  has_many :questions, dependent: :delete_all
  has_many :created_questions, class_name: 'Question', foreign_key: 'author_id'

  validates :name, presence: true
  validates :nickname, presence: true, uniqueness: true,
                       length: { maximum: 40 }, format: { with: NICKNAME_FORMAT }
  validates :email, presence: true, uniqueness: true,
                    format: { with: EMAIL_FORMAT }
  validates :header_color, format: { with: COLOR_FORMAT }

  before_validation :downcase_nickname

  has_secure_password

  def to_param
    nickname
  end

  private

  def downcase_nickname
    nickname&.downcase!
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: "You can't go there!"
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.with_questions.find_by!(text: params[:text])
    @questions = @hashtag.questions
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[update destroy edit hide]
  before_action :set_question_for_current_user, only: %i[update destroy edit hide]

  def new
    @user = User.find_by(nickname: params[:nickname])
    @question = Question.new(user: @user)
  end

  def create
    question_params = params.require(:question).permit(:body, :user_id)
    @question = Question.new(question_params)

    @question.author = current_user

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'New question has been created!'
    else
      flash.now[:alert] = 'You have incorrectly filled in the form'

      render :new
    end
  end

  def update
    question_params = params.require(:question).permit(:body, :answer, :hashtag)

    @question.update(question_params)

    redirect_to user_path(@question.user), notice: 'Question has been saved'
  end

  def destroy
    @user = @question.user
    @question.destroy

    redirect_to user_path(@user), notice: 'Question has been deleted'
  end

  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.last(10).reverse
    @users = User.last(10).reverse
    @hashtags = Hashtag.with_questions.all
  end

  def edit
  end

  def hide
    @question.update(hidden: true)
    redirect_to questions_path
  end

  private

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end

  def check_captcha(model)
    current_user.present? || verify_recaptcha(model: model)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'You are in!'
    else
      flash.now[:alert] = 'Wrong email or password'

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'You signed out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorise_user, only: %i[edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id

      redirect_to root_path, notice: 'You have successfully registered'
    else
      flash.now[:alert] = 'You have incorrectly filled in the form'

      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'Your data has been updated'
    else
      flash.now[:alert] = 'Please check the data'

      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: 'User has been destroyed'
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @question = Question.new(user: @user)
  end

  private

  def authorise_user
    redirect_with_alert unless current_user == @user
  end

  def set_user
    @user = User.find_by!(nickname: params[:nickname])
  end

  def user_params
    params.require(:user).permit(
      :name, :nickname, :email, :password, :password_confirmation, :header_color
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, many)
    count > 1 ? (return many) : (return one)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def render_with_hashtags(body)
    body.gsub(Hashtag::HASHTAG_FORMAT) { |word| link_to word, hashtag_path(word.downcase.delete('#')) }
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_nickname(user)
    "@#{user.nickname}"
  end
end

app/views/hashtags/show.html.erb
<div class="mt-sm container">
  <h2 class="title-lg my">
    Questions with hashtag: <%= content_tag :span, "##{sanitize @hashtag.text}", class: 'text-bold' %>
  </h2>
</div>

<% @questions.each do |question| %>
  <div class="mt-sm container">
    <%= render question %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <div class="navbar" style="background-color: <%= current_user&.header_color || '#370617' %>">
        <p class="title-sm text-bold"><%= link_to "Ask me!", root_path %></p>
        <div>
          <% if current_user.present? %>
            <%= link_to "@#{current_user.nickname}", user_path(current_user), class: "mr-sm" %>
            <%= button_to "Sign out", session_path, method: :delete %>
          <% else %>
            <%= link_to "Registration", new_user_path, class: "button button-yellow mr-sm" %>
            <%= link_to "Sign in", new_session_path, class: "button button-yellow" %>
          <% end %>
        </div>

      </div>
      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert].present?%>
        <p class="mb mt message message-notice"><%= flash[:alert] %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question, data: {turbo: false} do |form| %>
  <%= form.hidden_field :user_id %>
  <p><%= form.label :body, 'Question text' %></p>
  <p><%= form.text_area :body, rows: 5, class: "form-text-area" %></p>

  <% if question.persisted? %>
    <p class="mt"><%= form.label :answer, 'Your answer' %></p>
    <p><%= form.text_area :answer, rows: 5, class: "form-text-area" %></p>
  <% end %>

  <%= recaptcha_tags unless current_user.present? %>

  <p class="mt"><%= form.submit 'Save', class: 'button button-main' %></p>
<% end %>

app/views/questions/_question.html.erb
<% hidden_class = "text-pale" if question.hidden? %>
<%= content_tag :p, class: ["mb-sm", hidden_class] do %>
  <%= sanitize render_with_hashtags(question.body), tags: %w(a), attributes: %w(href) %>
<% end %>

<% if question.answer.present? %>
  <div class="mb-sm text-dark-red">
    <%= sanitize render_with_hashtags(question.answer), tags: %w(a), attributes: %w(href) %>
  </div>
<% end %>

<div class="text-sm question-footer">
  <div class="text-gray">
    <%= l(question.created_at, format: :short) %>
  </div>
  <div class="text-gray">
    <p class="mb text-sm text-grey">
      <% if question.author.nil?  %>
        <%= 'Question created by Anonymous' %>
      <% else %>
        <%= link_to "Question created by #{sanitize question.author.nickname}", user_path(question.author) %>
      <% end %>
    </p>
  </div>
  <% if current_user == question.user %>
    <div>
      <% edit_icon = (question.answer.present? ? 'pencil' : 'reply') %>
      <%= link_to fa_icon(edit_icon), edit_question_path(question),
                  title: 'Change question', class: 'mr-sm' %>
      <% unless question.hidden? %>
        <%= button_to fa_icon('eye-slash'), hide_question_path(question),
                    method: :put,
                    title: 'Hide question' %>
      <% end %>
      <%= button_to fa_icon('trash-o'), question_path(question),
                    method: :delete, title: 'Delete question',
                    form: {data: {turbo_confirm: 'Are you sure you want do delete the question?'}}  %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Edit of question <%= @question.id %></h2>

  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="container">
  <h2 class="title-lg mb">
    Recently added
  </h2>

  <div class="users-box">
    <% @users.each do |user| %>
      <%= render partial: 'users/user_avatar', locals: {user: user} %>
    <% end %>
  </div>
</div>

<div class="container mt-sm">
  <h2 class="title-lg mb">Hashtags</h2>
  <% @hashtags.each do |hashtag| %>
    <%= link_to hashtag.text, hashtag_path(hashtag.text) %>
  <% end %>
</div>

<div class="container mt-sm">
  <h2 class="title-lg mb">
    <%= "Last #{inclination(@questions.count, "Question", "Questions")}" %>
  </h2>
</div>

<% @questions.each do |question| %>
  <div class="mt-sm container" >
    <p class="mb text-sm text-grey">
      Question <%= link_to "#{question.id}", question_path(question) %>
      for user <%= link_to display_nickname(question.user), user_path(question.user) %>
    </p>
    <%= render question %>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb">New question</h2>
  <p class="mb"> for <%= link_to display_nickname(@question.user), user_path(@question.user) %></p>

  <% if @question.errors.any? %>
    <% @question.errors.full_messages.each do |message| %>
      <p class = "mb-sm text-red"><%= message %></p>
    <% end %>
  <% end %>

  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Question <%= @question.id %></h2>
  <p class="mt-sm"><%= link_to "All questions of #{display_nickname(@question.user)}", user_path(@question.user) %></p>
</div>

<div class="container mt-sm">
  <%= render 'question', question: @question %>
</div>

app/views/users/_no_questions.html.erb
<div class="container text-center">
  <p class="title-sm text-grey">
    This user has no questions yet
  </p>

  <div class="mt-lg mb-lg fa-4x text-light-grey">
    <%= fa_stacked_icon 'question', base: 'circle-o' %>
  </div>

  <%= link_to "Let me ask!", new_question_path(nickname: user),
              class: 'button button-main' %>
</div>

app/views/users/_user_avatar.html.erb
<% background_class = "users-box-user-bg#{user.id % 5}" %>

<div class="users-box-user <%= background_class %> rounded mr ml">
  <a href="<%= user_path(user) %>">
    <%= image_tag user.gravatar_url, title: display_nickname(user), class: 'rounded' %>
  </a>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title">User edit</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <p><%= image_tag @user.gravatar_url, title: "@#{@user.nickname}", class: 'rounded' %></p>
    <p class="text-sm">To change and update your avatar please register at:
      <%= link_to "Gravatar", 'https://gravatar.com' %> and upload your photo</p>
  </div>

  <div class="mt">
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <p><%= form.label :name, 'Name' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Nickname' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt-lg text-sm">If you do not want to update the password leave it blank!</p>

      <p class="mt"><%= form.label :password, 'Password' %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation, 'Password confirmation' %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :header_color, 'Header color' %></p>
      <p><%= form.color_field :header_color %></p>

      <p class="mt-lg">
        <%= form.submit "Save", class: 'button button-main' %>
        <span class="text-sm">or <%= link_to "Go back", :back %></span>
      </p>
    <% end %>
  </div>

  <div class="mt-lg">
    <%= button_to "Delete profile", user_path(@user),
                  method: :delete,
                  form: {data: {turbo_confirm: "Are you sure you want to delete your profile?"}},
                  class: 'text-red text-sm' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">Join and ask!</h2>

  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message| %>
      <p class = "mb-sm text-red"><%= message %></p>
    <% end %>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <p><%= form.label :name, "Your name" %></p>
      <p><%= form.text_field :name, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :nickname, "Nickname" %></p>
      <p><%= form.text_field :nickname, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: "form-text-field" %></p>

      <p class="mt-lg"><%= form.submit "Register", class: "button button-main" %></p>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-box">
  <h2 class="title-lg mt-lg"><%= sanitize @user.name %></h2>
  <p class="text-bold mt mb-lg"><%= sanitize display_nickname(@user) %></p>
  <div class="mt">
    <%= render partial: 'users/user_avatar', locals: {user: @user} %>
  </div>

  <% if current_user == @user %>
    <p class="mt mb-lg">
      <%= link_to fa_icon('pencil'), edit_user_path(@user) %>
    </p>
  <% end %>
</div>

<% if @questions.any? %>
  <div class="container">
    <p class="mt">
      <%= render'questions/form', question: @question %>
    </p>
  </div>

  <div class="container mt-sm">
    <h2 class="title-lg mb">
      <% @questions.count %>
      <%= inclination(@questions.count, "Question", "Questions") %>
    </h2>
  </div>

  <% @questions.each do |question| %>
    <div class="mt-sm container" >
      <%= render question %>
    </div>
  <% end %>
<% else %>
  <%= render partial: 'no_questions', locals: {user: @user} %>
<% end %>